apiVersion: v1
kind: Service
metadata:
  name: flask-demo-app
  labels:
    app: flask-demo-app
spec:
  type: LoadBalancer
  selector:
    app: flask-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

